---
abstract: 'Computes stemmed/POS tagged lists of text.'
author:
  - 'Jeff Kubina (jeff.kubina@gmail.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-StemTagPOS
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: 1.14
  Lingua::EN::Tagger: 0.15
  Lingua::Stem::Snowball: 0.952
version: 0.60
